name: npm-publish

on:
  workflow_dispatch:

jobs:
  call-update-workflow-local-repo:
    uses: noir-lang/noir/.github/workflows/update.yml@master
    secrets: inherit

  publish-npm:
    runs-on: ubuntu-22.04
    needs: call-update-workflow-local-repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: 'next'